version: '3'
services:
    eip-postgres:
        image: postgres:12
        container_name: lena-postgres
        restart: on-failure
        environment:
            POSTGRES_USER: lena
            POSTGRES_PASSWORD: lena_123
            POSTGRES_DB: lena_db
            POSTGRES_INITDB_ARGS: "--encoding='UTF-8'"
        volumes:
            - eip-postgres:/var/lib/postgresql/data
volumes:
  eip-postgres: