TIMESTAMP_FORMAT = "%d-%m-%Y"
PARTICIPANTS_QUEUE = "{}_participants_id_queue.csv"
DAILY_FRIENDS_CHECK_PATH = "{}_users_friends.csv"
STUDY_START_PATH = "{}_users_study_start.csv"
STUDY_INPUT_START_PART = "study_input.csv"
STUDY_END_PATH = "{}_users_study_end.csv"
USER_TRACKER_PATH = "user_tracker.csv"
DAILY_TWEETS_PATH = "{}_tweets.csv"
